---

- name: Enable NetworkManager
  ansible.builtin.service:
    name: NetworkManager.service
    state: started
    enabled: true

- name: Restart NeworkManager
  ansible.builtin.service:
    name: NetworkManager.service
    state: restarted
