---

- name: Arch Linux post-install
  hosts: hosts
  connection: local
  become: true

  roles:
    - { role: kernel, tags: ['kernel'] }
    - { role: base, tags: ['base'] }
    - { role: grub, tags: ['grub'] }
    - { role: x11, tags: ['x11'] }
    - { role: windowmanager, tags: ['windowmanager'] }
    - { role: network, tags: ['network'] }
    - { role: sound, tags: ['sound'] }
    - { role: power, tags: ['power'] }
    # - { role: applications, tags: ['applications'] }
    - { role: dotfiles, tags: ['dotfiles'] }
