---

- name: Install awesome + LightDM
  community.general.pacman:
    name:
      - awesome
      - lightdm
    state: present
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2

- name: Install fonts
  community.general.pacman:
    name:
      - ttf-dejavu
      - ttf-liberation
      - ttf-ibm-plex
      - ttf-ibmplex-mono-nerd
      - noto-fonts
      - noto-fonts-cjk
      - noto-fonts-emoji
      - fontconfig
      - xorg-font-util
    state: present
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2

- name: Install LightDM greeter + gtk3-classic
  aur:
    name:
      - gtk3-classic
      - lightdm-mini-greeter
    user: "{{ user.name }}"
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2

- name: Configure LightDM
  ansible.builtin.template:
    src: lightdm.conf.j2
    dest: /etc/lightdm/lightdm.conf
    backup: false
    owner: root
    group: root
    mode: "0644"

- name: Configure lightdm-mini-greeter
  ansible.builtin.template:
    src: lightdm-mini-greeter.conf.j2
    dest: /etc/lightdm/lightdm-mini-greeter.conf
    backup: false
    owner: root
    group: root
    mode: "0644"

- name: Enable LightDM service
  ansible.builtin.systemd:
    name: lightdm.service
    state: started
    enabled: true
