---

- name: Install awesomewm
  aur:
    name:
      - awesome-git
    user: "{{ user.name }}"
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2

- name: Install LightDM + acpid
  community.general.pacman:
    name:
      - lightdm
      - light-locker
      - acpid
    state: present
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2

- name: Install fonts
  community.general.pacman:
    name:
      - ttf-dejavu
      - ttf-liberation
      - ttf-ibm-plex
      - ttf-ibmplex-mono-nerd
      - noto-fonts
      - noto-fonts-cjk
      - noto-fonts-emoji
      - fontconfig
      - xorg-font-util
    state: present
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2

- name: Install gtk3-classic
  aur:
    name:
      - gtk3-classic
    user: "{{ user.name }}"
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2

- name: Install XDG utilities
  community.general.pacman:
    name:
      - xdg-utils
      - xdg-user-dirs
      - xdg-desktop-portal
      - xdg-desktop-portal-gtk
    state: present
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2

- name: Install polkit
  community.general.pacman:
    name:
      - polkit
      - polkit-gnome
    state: present
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2

- name: Install lightdm-mini-greeter
  aur:
    name:
      - lightdm-mini-greeter
    user: "{{ user.name }}"
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2

- name: Configure LightDM
  ansible.builtin.template:
    src: lightdm.conf.j2
    dest: /etc/lightdm/lightdm.conf
    backup: false
    owner: root
    group: root
    mode: "0644"

- name: Configure light-locker
  ansible.builtin.template:
    src: 99-light-locker.sh.j2
    dest: /etc/X11/xinit.d/99-light-locker.sh
    backup: false
    owner: root
    group: root
    mode: "0755"

- name: Configure lightdm-mini-greeter
  ansible.builtin.template:
    src: lightdm-mini-greeter.conf.j2
    dest: /etc/lightdm/lightdm-mini-greeter.conf
    backup: false
    owner: root
    group: root
    mode: "0644"

- name: Enable LightDM service
  ansible.builtin.systemd:
    name: lightdm.service
    state: started
    enabled: true

- name: Enable acpid service
  ansible.builtin.systemd:
    name: acpid.service
    state: started
    enabled: true
