---

- name: Install network utilities
  ansible.builtin.package:
    name:
      - ethtool
      - wpa_supplicant
      - networkmanager
      - network-manager-applet
      - networkmanager-openconnect
      - networkmanager-openvpn
    state: present
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2
  notify:
    - Enable NetworkManager
