# Pacman settings

pacman_mirrors:
  - https://us.arch.niranjan.co/$repo/os/$arch
  - https://losangeles.mirror.pkgbuild.com/$repo/os/$arch
  - https://mirror.givebytes.net/archlinux/$repo/os/$arch
  - https://opencolo.mm.fcix.net/archlinux/$repo/os/$arch
  - https://mnvoip.mm.fcix.net/archlinux/$repo/os/$arch
  - https://ohioix.mm.fcix.net/archlinux/$repo/os/$arch
  - https://forksystems.mm.fcix.net/archlinux/$repo/os/$arch
  - https://irltoolkit.mm.fcix.net/archlinux/$repo/os/$arch

pacman_parallel_downloads: 5


# NTP settings

ntp_servers: "0.pool.ntp.org 1.pool.ntp.org 2.pool.ntp.org 3.pool.ntp.org"

ntp_fallback: time.nist.gov
