---

- name: Install X11
  community.general.pacman:
    name:
      - xorg
      - mesa
      - mesa-utils
      - lib32-mesa
      - lib32-mesa-utils
    state: present
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2

- name: Install Intel GPU drivers
  community.general.pacman:
    name:
      - xf86-video-intel
      - intel-media-driver
      - libva-intel-driver
      - vulkan-intel
      - lib32-vulkan-intel
      - intel-compute-runtime
      - opencl-clover-mesa
    state: present
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2
  when: system.graphics_card == "intel"

- name: Install Nvidia GPU drivers
  community.general.pacman:
    name:
      - nvidia-open-dkms
      - nvidia-utils
      - lib32-nvidia-utils
      - cuda
      - opencl-nvidia
    state: present
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2
  when: system.graphics_card == "nvidia"

- name: Install AMD GPU drivers
  community.general.pacman:
    name:
      - xf86-video-amdgpu
      - mesa-vdpau
      - libva-mesa-driver
      - vulkan-radeon
      - lib32-vulkan-radeon
      - rocm-hip-runtime
      - rocm-hip-sdk
      - hip-runtime-amd
      - rocm-core
      - rocm-opencl-runtime
      - rocm-opencl-sdk
    state: present
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2
  when: system.graphics_card == "amd"
