---

# setup pacman

- name: Configure pacman mirrorlist
  ansible.builtin.template:
    src: mirrorlist.j2
    dest: /etc/pacman.d/
    backup: false
    owner: root
    group: root
    mode: "0644"

- name: Configure pacman
  ansible.builtin.template:
    src: pacman.conf.j2
    dest: /etc/pacman.conf
    backup: false
    owner: root
    group: root
    mode: "0644"

# install packages

- name: Perform full system upgrade
  community.general.pacman:
    update_cache: true
    upgrade: true
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2

- name: Install base packages
  community.general.pacman:
    name: "{{ base_packages }}"
    state: present
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2

- name: Install yay
  aur:
    name:
      - yay
      - yaycache
    user: "{{ user.name }}"
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2

- name: Install Intel microcode
  community.general.pacman:
    name: intel-ucode
    state: present
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2
  notify:
    - update grub
  when: system.processor == "intel"

- name: Install AMD microcode
  community.general.pacman:
    name: amd-ucode
    state: present
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2
  notify:
    - update grub
  when: system.processor == "amd"

# enable services

- name: Configure timesyncd
  ansible.builtin.template:
    src: timesyncd.conf.j2
    dest: /etc/systemd/timesyncd.conf
    backup: false
    owner: root
    group: root
    mode: "0644"

- name: Enable timesyncd
  ansible.builtin.systemd:
    name: systemd-timesyncd
    state: started
    enabled: true

- name: Enable fstrim timer
  ansible.builtin.systemd:
    name: fstrim.timer
    state: started
    enabled: true

- name: Enable paccache timer
  ansible.builtin.systemd:
    name: paccache.timer
    state: started
    enabled: true

- name: Enable yaycache timer
  ansible.builtin.systemd:
    name: yaycache.timer
    state: started
    enabled: true
