---

- name: Set timezone to {{ system.timezone }}
  community.general.timezone:
    name: "{{ system.timezone }}"

- name: Ensure the locale {{ system.locale }} exists
  community.general.locale_gen:
    name: "{{ system.locale }}"
    state: present
