---

- name: Set timezone to {{ system.timezone }}
  community.general.timezone:
    name: "{{ system.timezone }}"

- name: Set locale to {{ system.locale }}
  community.general.locale_gen:
    name: "{{ system.locale }}"
    state: present
