---

- name: Install pipewire + audio utilities
  community.general.pacman:
    name:
      - pipewire
      - lib32-pipewire
      - pipewire-audio
      - wireplumber
      - pipewire-alsa
      - pipewire-pulse
      - pipewire-jack
      - lib32-pipewire-jack
      - alsa-utils
      - pavucontrol
    state: present
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2
