---

- name: Grub configuration
  ansible.builtin.template:
    src: grub.j2
    dest: /etc/default/grub
    backup: false
    owner: root
    group: root
    mode: "0644"
  notify:
    - Update grub
